# Generated by Django 5.0.1 on 2024-01-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='numerical_order',
        ),
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=models.CharField(default=1, max_length=4),
        ),
    ]
